# Generated by Django 3.2.18 on 2023-03-21 19:06

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20230318_1551'),
        ('insuree_deceased', '0002_alter_insureedeceased_insuree'),
    ]

    operations = [
        migrations.CreateModel(
            name='InsureeDeceasedMutation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mutation', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='insuree_deceased', to='core.mutationlog')),
                ('policy_holder_insuree', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='mutations', to='insuree_deceased.insureedeceased')),
            ],
            options={
                'db_table': 'insuree_deceased_InsureeDeceasedMutation',
                'managed': True,
            },
        ),
    ]
