# Generated by Django 3.2.18 on 2023-03-28 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insuree', '0013_auto_20211103_1023'),
        ('insuree_deceased', '0004_auto_20230321_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insureedeceased',
            name='insuree',
            field=models.ForeignKey(blank=True, db_column='InsureeID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='deceased', to='insuree.insuree'),
        ),
    ]
